package br.com.pridecare.gui;

import br.com.pridecare.data.ReceitaMedicamentoService;
import br.com.pridecare.data.ReceitaService;
import br.com.pridecare.data.UsuarioService;
import javax.swing.JOptionPane;
import br.com.pridecare.model.Usuario;
import br.com.pridecare.model.Receita;
import br.com.pridecare.model.ReceitaMedicamento;
import br.com.pridecare.model.StatusReceita;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays;
import java.util.List;


/**
 * Classe TelaProntuario representa o prontuario do paciente.
 * <p>
 * Esta classe fornece a interface gráfica para que o medico insira o CPF e
 * retorne o nome do paciente na tabela. Alem, de um campo para preencher 
 * informações sobre o paciente que vão ser armazenados em uma coluna "prontuario" 
 * na tabela usuarios e os medicamentos e quantidades que vão ser armazenados na tabela "receita"
 * </p>
 *
 * @author oluca
 */
public class TelaProntuario extends javax.swing.JFrame {

    private Usuario pacienteSelecionado;
    private UsuarioService usuarioService = new UsuarioService();
    private ReceitaService receitaService = new ReceitaService();
    private ReceitaMedicamentoService receitaMedicamentoService = new ReceitaMedicamentoService();

    /**
     * Construtor da classe TelaProntuario. Inicializa os componentes gráficos da
     * tela de prontuario.
     */
    public TelaProntuario() {
        initComponents();
    }

    /**
     * Método para atualizar a tabela com o nome do paciente.
     *
     * @param pacientes lista de pacientes
     */
    private void atualizarTabela(List<Usuario> pacientes) {
        DefaultTableModel model = (DefaultTableModel) tabelaPacienteConsulta.getModel();
        model.setRowCount(0); // Limpar a tabela antes de adicionar novas linhas

        for (Usuario paciente : pacientes) {
            model.addRow(new Object[]{
                paciente.getNome()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        btnDeslogar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textCPF = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPacienteConsulta = new javax.swing.JTable();
        Receita = new javax.swing.JLabel();
        Receita1 = new javax.swing.JLabel();
        Receita2 = new javax.swing.JLabel();
        Receita3 = new javax.swing.JLabel();
        textMedicamento1 = new javax.swing.JTextField();
        textMedicamento2 = new javax.swing.JTextField();
        textMedicamento3 = new javax.swing.JTextField();
        Receita4 = new javax.swing.JLabel();
        textQuantidade = new javax.swing.JTextField();
        textQuantidade1 = new javax.swing.JTextField();
        textQuantidade2 = new javax.swing.JTextField();
        textAnotacao = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(100, 50, 150));

        btnDeslogar.setText("Deslogar");
        btnDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeslogarActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Anotações - Consulta:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Digite o CPF:");

        textCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCPFActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tabelaPacienteConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Nome"
            }
        ));
        jScrollPane2.setViewportView(tabelaPacienteConsulta);

        Receita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Receita.setForeground(new java.awt.Color(255, 255, 255));
        Receita.setText("Receita:");

        Receita1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Receita1.setForeground(new java.awt.Color(255, 255, 255));
        Receita1.setText("1. Uso Tópico:");

        Receita2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Receita2.setForeground(new java.awt.Color(255, 255, 255));
        Receita2.setText("2. Uso Tópico:");

        Receita3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Receita3.setForeground(new java.awt.Color(255, 255, 255));
        Receita3.setText("3. Uso Tópico:");

        textMedicamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMedicamento1ActionPerformed(evt);
            }
        });

        textMedicamento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMedicamento2ActionPerformed(evt);
            }
        });

        textMedicamento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMedicamento3ActionPerformed(evt);
            }
        });

        Receita4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Receita4.setForeground(new java.awt.Color(255, 255, 255));
        Receita4.setText("Quantidade:");

        textQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantidadeActionPerformed(evt);
            }
        });

        textQuantidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantidade1ActionPerformed(evt);
            }
        });

        textQuantidade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantidade2ActionPerformed(evt);
            }
        });

        textAnotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAnotacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(56, 56, 56)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeslogar)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Receita3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(425, 425, 425)
                                        .addComponent(textQuantidade2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(textMedicamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Receita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                            .addComponent(Receita2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(textMedicamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(textMedicamento3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 44, Short.MAX_VALUE))
                                            .addComponent(Receita1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textQuantidade1)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Receita4, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                                .addComponent(textQuantidade)))))
                                .addGap(31, 31, 31)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textAnotacao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(59, 59, 59))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnMenu)
                    .addComponent(btnDeslogar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(textAnotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Receita)
                    .addComponent(Receita4))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Receita1)
                    .addComponent(textMedicamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Receita2)
                    .addComponent(textMedicamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Receita3)
                    .addComponent(textMedicamento3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textQuantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeslogarActionPerformed
        JOptionPane.showMessageDialog(this, "Sessão encerrada. Até logo!");
        System.exit(0);
    }//GEN-LAST:event_btnDeslogarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        String medicamento1 = textMedicamento1.getText();
        String quantidade1 = textQuantidade.getText();
        String medicamento2 = textMedicamento2.getText();
        String quantidade2 = textQuantidade1.getText();
        String medicamento3 = textMedicamento3.getText();
        String quantidade3 = textQuantidade2.getText();

        String anotacao = textAnotacao.getText();

        // Lista de medicamentos e quantidades
        List<String> medicamentos = Arrays.asList(medicamento1, medicamento2, medicamento3);
        List<String> quantidadesStr = Arrays.asList(quantidade1, quantidade2, quantidade3);

        // Cria a receita e salva no banco de dados
        Receita receita = new Receita();
        receita.setCpfUsuario(pacienteSelecionado.getCpf());
        receita.setDataCriacao(new java.sql.Date(System.currentTimeMillis()));
        receita.setStatus(StatusReceita.DISPONIVEL);

        receitaService.salvarReceita(receita);

        // Salva os medicamentos e quantidades associados à receita, se houver
        for (int i = 0; i < medicamentos.size(); i++) {
            String medicamento = medicamentos.get(i);
            String quantidadeStr = quantidadesStr.get(i);

            if (!medicamento.isEmpty() && !quantidadeStr.isEmpty()) {
                int quantidade;
                try {
                    quantidade = Integer.parseInt(quantidadeStr);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Quantidade inválida para o medicamento: " + medicamento,
                            "Erro", JOptionPane.ERROR_MESSAGE);
                    continue;
                }

                ReceitaMedicamento receitaMedicamento = new ReceitaMedicamento();
                receitaMedicamento.setReceita(receita);
                receitaMedicamento.setMedicamento(medicamento);
                receitaMedicamento.setQuantidade(quantidade);

                receitaMedicamentoService.salvarReceitaMedicamento(receitaMedicamento);
            }
        }
        JOptionPane.showMessageDialog(this, "Receita salva com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void textCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCPFActionPerformed

    }//GEN-LAST:event_textCPFActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cpf = textCPF.getText().trim();

        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, digite o CPF.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Usuario paciente = usuarioService.buscarPorCpf(cpf);

        if (paciente == null) {
            JOptionPane.showMessageDialog(this, "Nenhum paciente encontrado para o CPF: " + cpf,
                    "Resultado da Busca", JOptionPane.INFORMATION_MESSAGE);
        } else {
            pacienteSelecionado = paciente;
            atualizarTabela(List.of(paciente));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void textMedicamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMedicamento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMedicamento1ActionPerformed

    private void textMedicamento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMedicamento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMedicamento2ActionPerformed

    private void textMedicamento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMedicamento3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMedicamento3ActionPerformed

    private void textQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantidadeActionPerformed

    private void textQuantidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantidade1ActionPerformed

    private void textQuantidade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantidade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantidade2ActionPerformed

    private void textAnotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAnotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAnotacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProntuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Receita;
    private javax.swing.JLabel Receita1;
    private javax.swing.JLabel Receita2;
    private javax.swing.JLabel Receita3;
    private javax.swing.JLabel Receita4;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDeslogar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabelaPacienteConsulta;
    private javax.swing.JTextField textAnotacao;
    private javax.swing.JTextField textCPF;
    private javax.swing.JTextField textMedicamento1;
    private javax.swing.JTextField textMedicamento2;
    private javax.swing.JTextField textMedicamento3;
    private javax.swing.JTextField textQuantidade;
    private javax.swing.JTextField textQuantidade1;
    private javax.swing.JTextField textQuantidade2;
    // End of variables declaration//GEN-END:variables
}
