package br.com.cenaflix.podcast.gui;

import br.com.cenaflix.podcast.service.PodcastService;
import br.com.cenaflix.podcast.Podcast;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 * Classe que representa a tela de cadastro de podcasts da aplicação Cenaflix.
 * Essa tela permite que os usuários insiram as informações necessárias para
 * cadastrar um novo podcast no sistema.
 *
 *  oluca
 */
public class CadastroPodcast extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPodcast
     */
    public CadastroPodcast() {
        initComponents();
        textProdutor.requestFocus();
    }

    /**
     * Limpa os campos de texto após o cadastro de um podcast.
     */
    private void limparCampos() {
        textProdutor.setText("");
        textNomeEpisodio.setText("");
        textNEpisodio.setText("");
        textDuracao.setText("");
        textURL.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cenaflix = new javax.swing.JLabel();
        CADASTRAR = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnVerListagem = new javax.swing.JButton();
        textURL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textDuracao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNEpisodio = new javax.swing.JTextField();
        textNomeEpisodio = new javax.swing.JTextField();
        textProdutor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cenaflix.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Cenaflix.setText("CENAFLIX");

        CADASTRAR.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CADASTRAR.setText("CADASTRAR PODCAST");

        btnCadastrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVerListagem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVerListagem.setText("Ver Listagem");
        btnVerListagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVerListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListagemActionPerformed(evt);
            }
        });

        textURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textURLActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("URL do repositório");

        textDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDuracaoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Duração");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Nº do Episódio");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Nome do Episódio");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Produtor");

        textNEpisodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNEpisodioActionPerformed(evt);
            }
        });

        textNomeEpisodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeEpisodioActionPerformed(evt);
            }
        });

        textProdutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textProdutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Cenaflix)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CADASTRAR)
                        .addGap(229, 229, 229))))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerListagem, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(textNEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(textURL)
                    .addComponent(textDuracao)
                    .addComponent(textNomeEpisodio)
                    .addComponent(textProdutor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Cenaflix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CADASTRAR)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addComponent(textNomeEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerListagem, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDuracaoActionPerformed

    private void textURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textURLActionPerformed
    /**
     * Ação realizada ao pressionar o botão de cadastrar. Coleta os dados do
     * formulário, cria um objeto Podcast e chama o serviço para salvar no banco
     * de dados.
     *
     * @param evt o evento de clique no botão Cadastrar
     */

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String produtor = textProdutor.getText();
        String nome = textNomeEpisodio.getText();
        int NumeroEpisodio = Integer.parseInt(textNEpisodio.getText());
        String duracao = textDuracao.getText();
        String urlRepositorio = textURL.getText();

        // Verifica se todos os campos estão preenchidos
        if (produtor.isEmpty() || nome.isEmpty() || textNEpisodio.getText().isEmpty()
                || duracao.isEmpty() || urlRepositorio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            PodcastService podcastService = new PodcastService();

            // Cria um novo objeto Podcast com os dados preenchidos
            Podcast novoPodcast = new Podcast();
            novoPodcast.setProdutor(produtor);
            novoPodcast.setNome(nome);
            novoPodcast.setNumeroEpisodio(NumeroEpisodio);
            novoPodcast.setDuracao(duracao);
            novoPodcast.setUrlRepositorio(urlRepositorio);

            // Chama o serviço para cadastrar o podcast
            podcastService.cadastrarPodcast(novoPodcast);

            JOptionPane.showMessageDialog(this, "Podcast cadastrado com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar podcast no banco de dados: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVerListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListagemActionPerformed
        abrirTelaListagem();
    }//GEN-LAST:event_btnVerListagemActionPerformed

    private void textNEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNEpisodioActionPerformed
        try {
            int numero_episodio = Integer.parseInt(textNEpisodio.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O campo 'Nº do Episódio' deve conter um número válido.",
                    "Erro de Formato", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_textNEpisodioActionPerformed

    private void textNomeEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeEpisodioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeEpisodioActionPerformed

    private void textProdutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textProdutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textProdutorActionPerformed

    private void abrirTelaListagem() {
        ListagemPodcast telaListagem = new ListagemPodcast();
        telaListagem.setVisible(true);
    }

    /**
     * Método principal que inicia a aplicação.
     * 
     * @param args os argumentos de linha de comando
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPodcast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CADASTRAR;
    private javax.swing.JLabel Cenaflix;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVerListagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textDuracao;
    private javax.swing.JTextField textNEpisodio;
    private javax.swing.JTextField textNomeEpisodio;
    private javax.swing.JTextField textProdutor;
    private javax.swing.JTextField textURL;
    // End of variables declaration//GEN-END:variables
}
