/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atividade2;

import data.FilmeDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * Classe principal da aplicação Cenaflix, responsável pela interface gráfica
 * e gerenciamento de ações relacionadas aos filmes.
 * 
 * @author oluca
 */
public class Cenaflix extends javax.swing.JFrame {

    /**
     * Construtor da classe Cenaflix que inicializa a interface gráfica.
     */
    public Cenaflix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NomeFilme = new javax.swing.JTextField();
        Categoria = new javax.swing.JTextField();
        Data = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Listagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CENAFLIX");

        jLabel2.setText("Nome do Filme:");

        jLabel3.setText("Data de Lançamento:");

        jLabel4.setText("Categoria:");

        NomeFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeFilmeActionPerformed(evt);
            }
        });

        Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActionPerformed(evt);
            }
        });

        Data.setText("___/___/_________");
        Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataActionPerformed(evt);
            }
        });

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("CADASTRO DE FILME");

        Listagem.setColumns(20);
        Listagem.setRows(5);
        jScrollPane2.setViewportView(Listagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(Cadastrar))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Limpar))
                            .addComponent(NomeFilme)
                            .addComponent(Categoria)
                            .addComponent(Data, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(136, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(131, 131, 131)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastrar)
                    .addComponent(Limpar)
                    .addComponent(Buscar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jLabel5)
                    .addContainerGap(320, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeFilmeActionPerformed
    /**
     * Ação que ocorre quando o botão Cadastrar é acionado.
     * Captura os dados do filme inseridos pelo usuário, valida os dados
     * e tenta cadastrar um novo filme no banco de dados.
     * 
     * @param evt o evento de ação que foi gerado ao clicar no botão
     */
    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        String nome = NomeFilme.getText();
        String categoria = Categoria.getText();
        String dataRecebida = Data.getText();

        if (nome.isEmpty() || categoria.isEmpty() || dataRecebida.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios!");
            return;
        }

        SimpleDateFormat conversor = new SimpleDateFormat("dd/MM/yyyy");
        java.sql.Date sqlDate;
        try {
            java.util.Date dataConvertida = conversor.parse(dataRecebida);
            sqlDate = new java.sql.Date(dataConvertida.getTime());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conversão da data: " + ex.getMessage());
            return;
        }

        Filme filme = new Filme(nome, categoria, sqlDate);

        FilmeDAO dao = new FilmeDAO();

        boolean statusConexao;
        try {
            statusConexao = dao.conectar();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar o driver de conexão: " + ex.getMessage());
            return;
        }

        if (!statusConexao) {
            JOptionPane.showMessageDialog(null, "Erro de conexão com o banco de dados.");
            return;
        }

        boolean inserido;
        try {
            inserido = dao.inserirFilme(filme);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar o filme: " + ex.getMessage());
            return;
        }

        if (inserido) {
            JOptionPane.showMessageDialog(null, "Filme cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar o filme.");
        }

        dao.desconectar();
    }//GEN-LAST:event_CadastrarActionPerformed
    /**
     * Ação que ocorre quando o botão Limpar é acionado.
     * Limpa todos os campos de entrada na interface gráfica.
     * 
     * @param evt o evento de ação que foi gerado ao clicar no botão
     */
    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        NomeFilme.setText("");
        Categoria.setText("");
        Data.setText("");
    }//GEN-LAST:event_LimparActionPerformed

    private void DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataActionPerformed

    private void CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaActionPerformed
     /**
     * Ação que ocorre quando o botão Buscar é acionado.
     * Realiza a busca de filmes no banco de dados com base no nome ou categoria.
     * Exibe os resultados na área de listagem.
     * 
     * @param evt o evento de ação que foi gerado ao clicar no botão
     */
    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String nome = NomeFilme.getText();
        String categoria = Categoria.getText();
        String dataRecebida = Data.getText();

        if (dataRecebida.isEmpty() && nome.isEmpty() && categoria.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, insira pelo menos um nome, categoria ou data para buscar.");
            return;
        }

        Listagem.setText("");

        FilmeDAO dao = new FilmeDAO();
        try {
            dao.conectar();

            List<Filme> filmes;

            if (!nome.isEmpty() && !categoria.isEmpty()) {
                filmes = dao.buscarFilmesPorNomeECategoria(nome, categoria);
            } else if (!nome.isEmpty()) {
                filmes = dao.buscarFilmesPorNome(nome);
            } else if (!categoria.isEmpty()) {
                filmes = dao.buscarFilmesPorCategoria(categoria);
            } else {
                if (!dataRecebida.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor, insira nome ou categoria junto com a data.");
                    return;
                }
                filmes = new ArrayList<>();
            }

            if (filmes.isEmpty()) {
                Listagem.append("Nenhum filme encontrado.\n");
            } else {
                for (Filme filme : filmes) {
                    Listagem.append("Filme: " + filme.getNome() + "\n");
                    Listagem.append("Categoria: " + filme.getCategoria() + "\n");
                    Listagem.append("Data de Lançamento: " + filme.getDataLancamento() + "\n");
                    Listagem.append("-----------------------------\n");
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar filmes: " + ex.getMessage() + ". Por favor, verifique se o banco de dados está acessível.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar o driver de conexão: " + ex.getMessage() + ". Verifique se o driver está incluído no projeto.");
        } finally {
            dao.desconectar();
        }
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * Método principal que inicia a aplicação.
     * 
     * @param args os argumentos de linha de comando
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cenaflix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cenaflix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cenaflix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cenaflix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cenaflix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JTextField Categoria;
    private javax.swing.JTextField Data;
    private javax.swing.JButton Limpar;
    private javax.swing.JTextArea Listagem;
    private javax.swing.JTextField NomeFilme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
